name: 'Vitest Evaluator'
description: 'Vitest Evaluator'
inputs:
  pr_author_username:
    description: 'Pull Request author username'
    required: true
outputs:
  result:
    description: "Vitest unit tests JSON results in base64 format."
    value: ${{steps.base64.outputs.result}}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - run: |
        cd $GITHUB_ACTION_PATH 
        npm install
      shell: bash
    
    - name: Run Vitest
      run: npx vitest --dir=src --reporter=json --outputFile.json=./evaluation.json --reporter=basic
      shell: bash
      continue-on-error: true

    - name: Run evaluator
      if: always()
      shell: bash
      env:
        INPUT_PR_AUTHOR_USERNAME: ${{inputs.pr_author_username}}
      run: node $GITHUB_ACTION_PATH/src/evaluator.js

    - name: Save output to base64
      if: always()
      id: base64
      shell: bash
      run: echo "result=`cat result.json | base64 -w 0`" >> $GITHUB_OUTPUT