name: 'Hello World'
description: 'Greet someone'
inputs:
  pr_author_username:
    description: 'Pull Request author username'
    required: true
outputs:
  result:
    description: "Vitest unit tests JSON results in base64 format."

runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.pr_author_username }}.
      shell: bash

    # - name: Setup Checkout
    #   uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - run: |
        cd $GITHUB_ACTION_PATH 
        npm install
      shell: bash
    
    - run: npx vitest --reporter=json --outputFile.json=./evaluation.json --reporter=basic
      shell: bash

    - name: Run evaluator
      if: always()
      shell: bash
      env:
        INPUT_PR_AUTHOR_USERNAME: ${{inputs.pr_author_username}}
      run: node $GITHUB_ACTION_PATH/src/evaluator.js

    - name: Save output to base64
      id: base64
      shell: bash
      run: pwd && echo "::set-output name=result::`cat result.json | base64 -w 0`"

    # - run: cat evaluation.json
    #   shell: bash

    # - name: Setup Checkout
    #   uses: actions/checkout@v3
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash
    # - run: goodbye.sh
    #   shell: bash

    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash

    # - name: Setup Checkout
    #   uses: actions/checkout@v3
    #     with: 
    #       path: 'evaluation.json'
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
