name: 'Hello World'
description: 'Greet someone'
inputs:
  pr_author_username:
    description: 'Pull Request author username'
    required: true
outputs:
  result:
    description: "Vitest unit tests JSON results in base64 format."

runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash