name: 'Hello World'
description: 'Greet someone'
inputs:
  pr_author_username:
    description: 'Pull Request author username'
    required: true
outputs:
  result:
    description: "Vitest unit tests JSON results in base64 format."

runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.pr_author_username }}.
      shell: bash

    # - name: Setup Checkout
    #   uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - run: |
        cd $GITHUB_ACTION_PATH 
        npm install
    
    - run: npx vitest --reporter=json --outputFile.json=./evaluation.json --reporter=basic
      shell: bash

    - run: cat evaluation.json
      shell: bash

    # - name: Setup Checkout
    #   uses: actions/checkout@v3
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash
    # - run: goodbye.sh
    #   shell: bash

    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash

    # - name: Setup Checkout
    #   uses: actions/checkout@v3
    #     with: 
    #       path: 'evaluation.json'
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Setup Checkout
      uses: actions/checkout@v3
      with:
        repository: betrybe/vitest2-evaluator-action
